[package]
name = "micro_donations"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.1.0"

[dev-dependencies]
soroban-sdk = { version = "21.1.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]